### ISSUE TITLE
DiskRead

### ISSUE THREAD

**Issue by anic17** [Ruzie/DriveRead#1]
Thanks for using my program [DiskRead,](https://github.com/anic17/DiskRead) it would be nice if you added me in the program credits.

This is an obvious violation of the GNU GPL v3.0 licence. If you do not add credit (or remove this repository) I will have to take legal action.

**Comment by Ruzie** [comment]
Hey there, my apologies for not adding the real source, I'd like to add, thank you for reminding me.

**Comment by Ruzie** [comment]
Again, deep apologise for not adding the credits, and I've made some little changes and a bit elaborate more about it, thanks for creating it!

Note: I've added the credit on repo README.
